[2023-02-18T00:02:21.072+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2023-02-18T00:02:19.511325+00:00 [queued]>
[2023-02-18T00:02:21.080+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2023-02-18T00:02:19.511325+00:00 [queued]>
[2023-02-18T00:02:21.081+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T00:02:21.083+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-18T00:02:21.084+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T00:02:21.093+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): load_data> on 2023-02-18 00:02:19.511325+00:00
[2023-02-18T00:02:21.099+0000] {standard_task_runner.py:55} INFO - Started process 1027 to run task
[2023-02-18T00:02:21.104+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'manual__2023-02-18T00:02:19.511325+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmpisa2749c']
[2023-02-18T00:02:21.105+0000] {standard_task_runner.py:83} INFO - Job 153: Subtask load_data
[2023-02-18T00:02:21.169+0000] {task_command.py:388} INFO - Running <TaskInstance: booking_ingestion.load_data manual__2023-02-18T00:02:19.511325+00:00 [running]> on host f01ad4775be8
[2023-02-18T00:02:21.220+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-18T00:02:19.511325+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-18T00:02:19.511325+00:00
[2023-02-18T00:02:21.223+0000] {sql.py:254} INFO - Executing: 
             CREATE TABLE IF NOT EXISTS booking_record (
                    client_id INTEGER NOT NULL,
                    booking_date TEXT NOT NULL,
                    room_type TEXT(512) NOT NULL,
                    hotel_id INTEGER NOT NULL,
                    booking_cost NUMERIC,
                    currency TEXT,
                    age INTEGER,
                    client_name TEXT(512),
                    client_type TEXT(512),
                    hotel_name TEXT(512));
          
[2023-02-18T00:02:21.240+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-18T00:02:21.244+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=load_data, execution_date=20230218T000219, start_date=20230218T000221, end_date=20230218T000221
[2023-02-18T00:02:21.255+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 153 for task load_data (The conn_id `postgres_default` isn't defined; 1027)
[2023-02-18T00:02:21.275+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-18T00:02:21.293+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
